export const dataSkills = [
  {
    id: 1,
    name: "C++",
    work: "Language",
    testimonial: "Good experience with this language",
    image: "/assets/c++.png",
  },
  {
    id: 2,
    name: "Python",
    work: "Language",
    testimonial: "Good experience with this language",
    image: "/assets/python.png",
  },
  {
    id: 3,
    name: "MySql",
    work: "Database",
    testimonial: "Good experience with this database",
    image: "/assets/mysql.svg",
  },
  {
    id: 4,
    name: "JavaScript",
    work: "Language",
    testimonial: "Some experience with this language",
    image: "/assets/javascript2.png",
  },
  {
    id: 5,
    name: "Firebase",
    work: "Database",
    testimonial: "Medium experience with this database",
    image: "/assets/firebase.png",
  },
  {
    id: 6,
    name: "React",
    work: "Framework",
    testimonial: "Some experience with this framework",
    image: "/assets/react.png",
  },
  {
    id: 7,
    name: "GitHub",
    work: "VCS",
    testimonial: "Good experience with this Version Control System",
    image: "/assets/github3.png",
  },
  {
    id: 8,
    name: "Node.js",
    work: "Technology",
    testimonial: "Some experience with this technology",
    image: "/assets/nodejs.png",
  },
  {
    id: 9,
    name: "Clojure",
    work: "Language",
    testimonial: "Medium experience with this technology",
    image: "/assets/Clojure.png",
  },
];
